server:
  port: 8763
spring:
  application:
    name: hello oauth srv
security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"